version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '4001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: api_dotnet_ddd
    volumes:
      - './volumes/mysql:/var/lib/mysql'
